---
- hosts: dvcs_servers

  tasks:

    - name: Test repo tools
      repobackup: repodir={{ repodir }}
      register: retval

    - name: Save result to file
      local_action: copy content="{{ retval.repos|to_json }}" dest=./results.txt

    - name: Provide CSV
      local_action: shell ./json2csv.py < results.txt > results.csv

